apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: topics.kafka.benjamin-borbe.de
spec:
  conversion:
    strategy: None
  group: kafka.benjamin-borbe.de
  names:
    kind: Topic
    listKind: TopicList
    plural: topics
    singular: topic
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
